readme
LivesInRoom29/ConnectChore pull request #53
Opened 2020-12-04 21:58 UTC by ARam2142

A user story has been added to readme. A link within the table of contents is now visible.

2020-12-04 22:23 UTC, hilbug requested changes
Andres- Since User Stories are development-focused, can you move them later in the read-me, so the app description is first in the readme? Let's have them listed before Future Enhancements. Let me know if you have any questions.

2020-12-04 22:50 UTC, ARam2142 commented
its fixed

2020-12-05 19:19 UTC, hilbug requested changes
Remove this from table of contents: [User Stories](#user-stores)

Add space between the "-" and the first word in the future enhancements section, so that they display as bullet points.  Example: - Make ...

2020-12-05 19:21 UTC, hilbug approved these changes

2020-12-05 19:21 UTC, merged